package testReport.daos;

import java.util.List;
import testReport.mapper.Aa01;

public interface Aa01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa01
     *
     * @mbggenerated Sat Oct 13 23:56:04 CST 2018
     */
    int insert(Aa01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa01
     *
     * @mbggenerated Sat Oct 13 23:56:04 CST 2018
     */
    List<Aa01> selectAll();
}