package testReport.daos;

import java.util.List;
import testReport.mapper.Aa02;

public interface Aa02Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa02
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    int insert(Aa02 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aa02
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    List<Aa02> selectAll();
}