package testReport.daos;

import java.util.List;
import java.util.Map;

import testReport.mapper.Ab01;

public interface Ab01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab01
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    int insert(Ab01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ab01
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    List<Ab01> selectAll();
    
    Ab01 getUserId(int id);
}