package testReport.mapper;

public class Aa01 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa01.aaa001
     *
     * @mbggenerated Sat Oct 13 23:56:04 CST 2018
     */
    private String aaa001;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa01.aaa001
     *
     * @return the value of aa01.aaa001
     *
     * @mbggenerated Sat Oct 13 23:56:04 CST 2018
     */
    public String getAaa001() {
        return aaa001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa01.aaa001
     *
     * @param aaa001 the value for aa01.aaa001
     *
     * @mbggenerated Sat Oct 13 23:56:04 CST 2018
     */
    public void setAaa001(String aaa001) {
        this.aaa001 = aaa001;
    }
}