package testReport.mapper;

public class Aa02 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa02.AAA021
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    private Integer aaa021;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa02.AAA022
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    private String aaa022;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aa02.AAA023
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    private String aaa023;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa02.AAA021
     *
     * @return the value of aa02.AAA021
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    public Integer getAaa021() {
        return aaa021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa02.AAA021
     *
     * @param aaa021 the value for aa02.AAA021
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    public void setAaa021(Integer aaa021) {
        this.aaa021 = aaa021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa02.AAA022
     *
     * @return the value of aa02.AAA022
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    public String getAaa022() {
        return aaa022;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa02.AAA022
     *
     * @param aaa022 the value for aa02.AAA022
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    public void setAaa022(String aaa022) {
        this.aaa022 = aaa022;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aa02.AAA023
     *
     * @return the value of aa02.AAA023
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    public String getAaa023() {
        return aaa023;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aa02.AAA023
     *
     * @param aaa023 the value for aa02.AAA023
     *
     * @mbggenerated Mon Oct 15 22:18:13 CST 2018
     */
    public void setAaa023(String aaa023) {
        this.aaa023 = aaa023;
    }
}