package testReport.mapper;

public class Ab01 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab01.AAB011
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    private Integer aab011;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab01.AAB012
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    private String aab012;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab01.AAB013
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    private String aab013;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab01.AAB014
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    private Integer aab014;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab01.AAB015
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    private String aab015;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab01.AAB016
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    private Integer aab016;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab01.AAB017
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    private Integer aab017;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab01.AAB018
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    private Integer aab018;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ab01.AAB019
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    private Integer aab019;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab01.AAB011
     *
     * @return the value of ab01.AAB011
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public Integer getAab011() {
        return aab011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab01.AAB011
     *
     * @param aab011 the value for ab01.AAB011
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public void setAab011(Integer aab011) {
        this.aab011 = aab011;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab01.AAB012
     *
     * @return the value of ab01.AAB012
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public String getAab012() {
        return aab012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab01.AAB012
     *
     * @param aab012 the value for ab01.AAB012
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public void setAab012(String aab012) {
        this.aab012 = aab012;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab01.AAB013
     *
     * @return the value of ab01.AAB013
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public String getAab013() {
        return aab013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab01.AAB013
     *
     * @param aab013 the value for ab01.AAB013
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public void setAab013(String aab013) {
        this.aab013 = aab013;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab01.AAB014
     *
     * @return the value of ab01.AAB014
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public Integer getAab014() {
        return aab014;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab01.AAB014
     *
     * @param aab014 the value for ab01.AAB014
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public void setAab014(Integer aab014) {
        this.aab014 = aab014;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab01.AAB015
     *
     * @return the value of ab01.AAB015
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public String getAab015() {
        return aab015;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab01.AAB015
     *
     * @param aab015 the value for ab01.AAB015
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public void setAab015(String aab015) {
        this.aab015 = aab015;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab01.AAB016
     *
     * @return the value of ab01.AAB016
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public Integer getAab016() {
        return aab016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab01.AAB016
     *
     * @param aab016 the value for ab01.AAB016
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public void setAab016(Integer aab016) {
        this.aab016 = aab016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab01.AAB017
     *
     * @return the value of ab01.AAB017
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public Integer getAab017() {
        return aab017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab01.AAB017
     *
     * @param aab017 the value for ab01.AAB017
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public void setAab017(Integer aab017) {
        this.aab017 = aab017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab01.AAB018
     *
     * @return the value of ab01.AAB018
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public Integer getAab018() {
        return aab018;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab01.AAB018
     *
     * @param aab018 the value for ab01.AAB018
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public void setAab018(Integer aab018) {
        this.aab018 = aab018;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ab01.AAB019
     *
     * @return the value of ab01.AAB019
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public Integer getAab019() {
        return aab019;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ab01.AAB019
     *
     * @param aab019 the value for ab01.AAB019
     *
     * @mbggenerated Sun Oct 14 22:10:25 CST 2018
     */
    public void setAab019(Integer aab019) {
        this.aab019 = aab019;
    }
}